### ISSUE TITLE
Add support for .swiftformat config file

### ISSUE THREAD

**Issue by godbout** [aerobounce/Sublime-Swift-Format#1]
seems to work great when there is no config file, but the plugin ignores it when there is one. am i missing something? thanks!

**Comment by aerobounce** [comment]
No you're not, currently the plugin does not support `.swiftformat` nor I ever use config files so I'm not good at how it works...
Since you're processing 'a' file being opened with ST3 but not a directory, so not quire sure what implementation would fit. 🤔

**Comment by godbout** [comment]
> Since you're processing 'a' file being opened with ST3 but not a directory, so not quire sure what implementation would fit. 🤔

ah, i see. makes sense then. i guess most of the plugins i use run the command from the project root directory, where the config files usually are. if they're somewhere else then for sure the command allows a custom folder through some parameter. i thought your plugin was about the same, a kind of wrapper around the command itself.

thanks for your time!

**Comment by aerobounce** [comment]
Well, `swiftformat` has a `--config "path/to/config/file"` option, so it might be a good idea to add support for it.

> i guess most of the plugins i use run the command from the project root directory, where the config files usually are

Could you introduce them, so I might be able to learn from them and add a feature, something like "Automatic config file detection".

**Comment by godbout** [comment]
from the top of my mind:

* https://github.com/gerardroche/sublime-phpunit
* https://github.com/SublimeLinter/SublimeLinter-phpcs
* https://github.com/adael/SublimePhpCsFixer

but i just assume. will update if i think of something else. let me know if some other info may help.

**Comment by aerobounce** [comment]
Thanks for the info and being cooperative. I think I'm getting some idea. 👍 

edit: As I have a direction now, edited the issue title accordingly.

**Comment by godbout** [comment]
hey no worries 👍🏼️ thanks for the time spent!

**Comment by aerobounce** [comment]
It's been a bit while. I've pushed config file support implementations to master ~(not tagged yet)~, could you try it out?
I think it's working pretty well so far.

edit: It is now tagged and you should be able to fetch update to v1.2.0 when it's available from packagecontrol.

**Comment by godbout** [comment]
thanks! will try later tonight (in about 7/8 hours here).

**Comment by godbout** [comment]
i can confirm that this works beautifully. thanks!

**Comment by aerobounce** [comment]
Great! Thanks for letting me know.
